/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the  "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * @author : Ammar Shadiq, Filip Antomonov
 * Information Retrieval Lab 1: Inverted Index, Boolean Query, Weighted Query
 * Uppsala University, April 2016
 */
package infretlab1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;

/**
 *
 * @author shadiq
 */
public class SimpleDocumentQuery extends javax.swing.JFrame {

    /**
     * Creates new form SimpleDocumentQuery
     */
    public SimpleDocumentQuery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corpusFileBrowseButton = new javax.swing.JButton();
        corpusFileTextField = new javax.swing.JTextField();
        indexFileButton = new javax.swing.JButton();
        MainTabbedPane = new javax.swing.JTabbedPane();
        TokenStatPanel = new javax.swing.JPanel();
        numOfDocStaticLabel = new javax.swing.JLabel();
        numOfTokStaticLabel = new javax.swing.JLabel();
        numOfUniqTokStaticLabel = new javax.swing.JLabel();
        numOfDocsLabel = new javax.swing.JLabel();
        numOfTokensLabel = new javax.swing.JLabel();
        numOfUniqTokensLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenStatTable = new javax.swing.JTable();
        booleanQueryPanel = new javax.swing.JPanel();
        booleanQueriesTextField = new javax.swing.JTextField();
        booleanSearchButton = new javax.swing.JButton();
        booleanQueryScrollPane = new javax.swing.JScrollPane();
        booleanQueryResultTable = new javax.swing.JTable();
        bQueryResultLabel = new javax.swing.JLabel();
        bQueryResultNum = new javax.swing.JLabel();
        bQueryCompLabel = new javax.swing.JLabel();
        bQueryCompNum = new javax.swing.JLabel();
        optimizeQueryBooleanCheckBox = new javax.swing.JCheckBox();
        weightedQueryPanel = new javax.swing.JPanel();
        weightedQueryTextField = new javax.swing.JTextField();
        weightedSearchButton = new javax.swing.JButton();
        weightedQueryScrollPane = new javax.swing.JScrollPane();
        weightedQueryResultTable = new javax.swing.JTable();
        wQueryResultLabel = new javax.swing.JLabel();
        wQueryResultNum = new javax.swing.JLabel();
        wQueryCompLabel = new javax.swing.JLabel();
        wQueryCompNum = new javax.swing.JLabel();
        optimizeQueryWeightedCheckBox = new javax.swing.JCheckBox();
        aboutPanel = new javax.swing.JPanel();
        AuthorLabel = new javax.swing.JLabel();
        courseLabel = new javax.swing.JLabel();
        labIdLabel = new javax.swing.JLabel();
        lowerCaseCheckBox = new javax.swing.JCheckBox();
        filterPunctCheckBox = new javax.swing.JCheckBox();
        filterStopCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IR Lab 1 - Uppsala Univ");

        corpusFileBrowseButton.setText("Browse");
        corpusFileBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corpusFileBrowseButtonActionPerformed(evt);
            }
        });

        corpusFileTextField.setText("movies.txt");

        indexFileButton.setText("Index It!");
        indexFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexFileButtonActionPerformed(evt);
            }
        });

        numOfDocStaticLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numOfDocStaticLabel.setText("Documents (Line)");

        numOfTokStaticLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numOfTokStaticLabel.setText("Tokens");

        numOfUniqTokStaticLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numOfUniqTokStaticLabel.setText("Unique Tokens");

        numOfDocsLabel.setText("0");

        numOfTokensLabel.setText("0");

        numOfUniqTokensLabel.setText("0");

        tokenStatTable.setAutoCreateRowSorter(true);
        tokenStatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Token", "Freq", "Doc Freq"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tokenStatTable);
        if (tokenStatTable.getColumnModel().getColumnCount() > 0) {
            tokenStatTable.getColumnModel().getColumn(0).setPreferredWidth(4);
        }

        javax.swing.GroupLayout TokenStatPanelLayout = new javax.swing.GroupLayout(TokenStatPanel);
        TokenStatPanel.setLayout(TokenStatPanelLayout);
        TokenStatPanelLayout.setHorizontalGroup(
            TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TokenStatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(TokenStatPanelLayout.createSequentialGroup()
                        .addGroup(TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TokenStatPanelLayout.createSequentialGroup()
                                .addComponent(numOfTokensLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfTokStaticLabel))
                            .addGroup(TokenStatPanelLayout.createSequentialGroup()
                                .addComponent(numOfUniqTokensLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfUniqTokStaticLabel))
                            .addGroup(TokenStatPanelLayout.createSequentialGroup()
                                .addComponent(numOfDocsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numOfDocStaticLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TokenStatPanelLayout.setVerticalGroup(
            TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TokenStatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfDocsLabel)
                    .addComponent(numOfDocStaticLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfTokStaticLabel)
                    .addComponent(numOfTokensLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TokenStatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfUniqTokStaticLabel)
                    .addComponent(numOfUniqTokensLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Tokens Stat", TokenStatPanel);

        booleanQueriesTextField.setText("really kids school");
        booleanQueriesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanQueriesTextFieldActionPerformed(evt);
            }
        });

        booleanSearchButton.setText("Search!");
        booleanSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booleanSearchButtonActionPerformed(evt);
            }
        });

        booleanQueryResultTable.setDefaultRenderer(String.class, new MultiLineTableCellRenderer());
        booleanQueryResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc ID", "Content"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        booleanQueryResultTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        booleanQueryScrollPane.setViewportView(booleanQueryResultTable);
        if (booleanQueryResultTable.getColumnModel().getColumnCount() > 0) {
            booleanQueryResultTable.getColumnModel().getColumn(0).setMinWidth(70);
            booleanQueryResultTable.getColumnModel().getColumn(0).setPreferredWidth(70);
            booleanQueryResultTable.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        bQueryResultLabel.setText("Result:");

        bQueryResultNum.setText("0");

        bQueryCompLabel.setText("# Comparison:");

        bQueryCompNum.setText("0");

        optimizeQueryBooleanCheckBox.setText("Optimize Comparison");

        javax.swing.GroupLayout booleanQueryPanelLayout = new javax.swing.GroupLayout(booleanQueryPanel);
        booleanQueryPanel.setLayout(booleanQueryPanelLayout);
        booleanQueryPanelLayout.setHorizontalGroup(
            booleanQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanQueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booleanQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booleanQueryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(booleanQueryPanelLayout.createSequentialGroup()
                        .addComponent(booleanQueriesTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booleanSearchButton))
                    .addGroup(booleanQueryPanelLayout.createSequentialGroup()
                        .addComponent(bQueryResultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bQueryResultNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bQueryCompLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bQueryCompNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optimizeQueryBooleanCheckBox)))
                .addContainerGap())
        );
        booleanQueryPanelLayout.setVerticalGroup(
            booleanQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booleanQueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(booleanQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(booleanQueriesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booleanSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(booleanQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bQueryResultLabel)
                    .addComponent(bQueryResultNum)
                    .addComponent(bQueryCompLabel)
                    .addComponent(bQueryCompNum)
                    .addComponent(optimizeQueryBooleanCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(booleanQueryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Boolean Queries", booleanQueryPanel);

        weightedQueryTextField.setText("really kids school");
        weightedQueryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightedQueryTextFieldActionPerformed(evt);
            }
        });

        weightedSearchButton.setText("Search!");
        weightedSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightedSearchButtonActionPerformed(evt);
            }
        });

        weightedQueryResultTable.setAutoCreateRowSorter(true);
        weightedQueryResultTable.setDefaultRenderer(String.class, new MultiLineTableCellRenderer());
        weightedQueryResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Doc ID", "Content", "CosSim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        weightedQueryScrollPane.setViewportView(weightedQueryResultTable);
        if (weightedQueryResultTable.getColumnModel().getColumnCount() > 0) {
            weightedQueryResultTable.getColumnModel().getColumn(0).setMinWidth(10);
            weightedQueryResultTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            weightedQueryResultTable.getColumnModel().getColumn(0).setMaxWidth(150);
            weightedQueryResultTable.getColumnModel().getColumn(1).setMinWidth(10);
            weightedQueryResultTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            weightedQueryResultTable.getColumnModel().getColumn(1).setMaxWidth(150);
            weightedQueryResultTable.getColumnModel().getColumn(3).setMinWidth(10);
            weightedQueryResultTable.getColumnModel().getColumn(3).setPreferredWidth(70);
            weightedQueryResultTable.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        wQueryResultLabel.setText("Result:");

        wQueryResultNum.setText("0");

        wQueryCompLabel.setText("# Comparison:");

        wQueryCompNum.setText("0");

        optimizeQueryWeightedCheckBox.setText("Optimize Comparison");

        javax.swing.GroupLayout weightedQueryPanelLayout = new javax.swing.GroupLayout(weightedQueryPanel);
        weightedQueryPanel.setLayout(weightedQueryPanelLayout);
        weightedQueryPanelLayout.setHorizontalGroup(
            weightedQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightedQueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(weightedQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightedQueryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addGroup(weightedQueryPanelLayout.createSequentialGroup()
                        .addComponent(weightedQueryTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weightedSearchButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, weightedQueryPanelLayout.createSequentialGroup()
                        .addComponent(wQueryResultLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wQueryResultNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wQueryCompLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wQueryCompNum, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(optimizeQueryWeightedCheckBox)))
                .addContainerGap())
        );
        weightedQueryPanelLayout.setVerticalGroup(
            weightedQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightedQueryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(weightedQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weightedQueryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightedSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(weightedQueryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wQueryResultLabel)
                    .addComponent(wQueryResultNum)
                    .addComponent(wQueryCompLabel)
                    .addComponent(wQueryCompNum)
                    .addComponent(optimizeQueryWeightedCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weightedQueryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainTabbedPane.addTab("Weighted Query", weightedQueryPanel);

        AuthorLabel.setText("Author: Ammar Shadiq, Filip Antomonov");

        courseLabel.setText("Information Retrieval, Uppsala University, April 2016");

        labIdLabel.setText("Lab 1: Inverted Index, Boolean Query, Weighted Query");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AuthorLabel)
                    .addComponent(courseLabel)
                    .addComponent(labIdLabel))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AuthorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(courseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labIdLabel)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        MainTabbedPane.addTab("About", aboutPanel);

        lowerCaseCheckBox.setSelected(true);
        lowerCaseCheckBox.setText("lower case the tokens");

        filterPunctCheckBox.setSelected(true);
        filterPunctCheckBox.setText("filter punctuations");

        filterStopCheckBox.setSelected(true);
        filterStopCheckBox.setText("filter stopwords");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corpusFileBrowseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(corpusFileTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lowerCaseCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterPunctCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterStopCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(indexFileButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corpusFileBrowseButton)
                    .addComponent(corpusFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowerCaseCheckBox)
                    .addComponent(filterPunctCheckBox)
                    .addComponent(filterStopCheckBox)
                    .addComponent(indexFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void indexFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexFileButtonActionPerformed
        boolean isLowerCased = lowerCaseCheckBox.isSelected();
        boolean ignoreStopWords = filterStopCheckBox.isSelected();
        boolean ignorePuctuations = filterPunctCheckBox.isSelected();
        indexTheFile(corpusFileTextField.getText(), isLowerCased, ignoreStopWords, ignorePuctuations);        
        updateTokenStatDisplay();
    }//GEN-LAST:event_indexFileButtonActionPerformed

    private void booleanSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanSearchButtonActionPerformed
        String query = booleanQueriesTextField.getText().toLowerCase();
        if(invertedIndex != null && !query.isEmpty()){
            Set<Integer> resultSet = booleanSearchDocuments(query, optimizeQueryBooleanCheckBox.isSelected(), bQueryCompNum);
            updateBooleanQueriesResultTable(resultSet);
        }
    }//GEN-LAST:event_booleanSearchButtonActionPerformed

    private void weightedSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightedSearchButtonActionPerformed
        String query = weightedQueryTextField.getText().toLowerCase();
        if(invertedIndex != null && !query.isEmpty()){
            Map<Integer, Double> resultMap = weightedSearchDocuments(query, optimizeQueryWeightedCheckBox.isSelected(), wQueryCompNum);
            updateWeigtedQueriesResultTable(resultMap);
        }
    }//GEN-LAST:event_weightedSearchButtonActionPerformed

    private void corpusFileBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corpusFileBrowseButtonActionPerformed
        FILECHOOSER.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int r = FILECHOOSER.showOpenDialog(this);
        if (r != javax.swing.JFileChooser.APPROVE_OPTION) {
            return;
        }
        corpusFileTextField.setText(FILECHOOSER.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_corpusFileBrowseButtonActionPerformed

    private void booleanQueriesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booleanQueriesTextFieldActionPerformed
        booleanSearchButtonActionPerformed(evt);
    }//GEN-LAST:event_booleanQueriesTextFieldActionPerformed

    private void weightedQueryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightedQueryTextFieldActionPerformed
        weightedSearchButtonActionPerformed(evt);
    }//GEN-LAST:event_weightedQueryTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleDocumentQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleDocumentQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleDocumentQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleDocumentQuery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleDocumentQuery().setVisible(true);
            }
        });
    }
    
    /**
     * Read and index the file
     * @param fileString file location string
     * @param isLowerCased should it lower cased?
     * @param ignoreStopWords should it filter stopwords?
     * @param ignorePuctuations should it filter punctuations?
     */
    private void indexTheFile(String fileString, boolean isLowerCased, boolean ignoreStopWords, boolean ignorePuctuations) {
        // Reset local variable!
        invertedIndex = new HashMap<>();
        tokenFreq = new HashMap<>();
        documents = new HashMap<>();
        numOfDoc = 0;
        numOfToken = 0;
        
        try {
            // read the file
            BufferedReader br = new BufferedReader(new FileReader(fileString));
            ArrayList<Document> docs = new ArrayList<>();
            
            int lineCounter = 0;
            int tokenCounter = 0;

            String line = null;
            while ((line = br.readLine()) != null) {
                
                if(isLowerCased) line = line.toLowerCase(); // to lower case
                String[] tokens = line.split(" "); // tokenize
                if(ignoreStopWords | ignorePuctuations) tokens = filterTokens(tokens, ignoreStopWords, ignorePuctuations);
                
                // for counting & Document ID purpose
                lineCounter ++;
                tokenCounter += tokens.length;
                
                // Document storage for retrieval use
                documents.put(lineCounter, createDocument(line, tokens, lineCounter));
                
                // index the document
                indexDocument(tokens, lineCounter);
            }
            
            /* calculate documents TF-IDF values */
            generateTFIDF();
            
            /* UPDATE STATISTICS */
            numOfDoc = lineCounter;
            numOfToken = tokenCounter;
            
            br.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Filtering tokens from specified stopwords and puctuations
     * @param tokens a list of tokens
     * @param ignoreStopWords should it filter stopwords
     * @param ignorePuctuations should it filter punctuations
     * @return an array of filtered tokens
     */
    private static String[] filterTokens(String[] tokens, boolean ignoreStopWords, boolean ignorePuctuations){
        ArrayList<String> tokenList = new ArrayList<>(Arrays.asList(tokens));
        Set<String> filterSet = new HashSet<>();
        if(ignorePuctuations) filterSet.addAll(PUNCTUATIONSET);
        if(ignoreStopWords) filterSet.addAll(STOPWORDSET);
        
        tokenList.removeAll(filterSet);
        
        return tokenList.toArray(new String[0]);
    }
    
    /**
     * Simple interface for creating a document object
     * @param docContent
     * @param tokens
     * @param docId
     * @return 
     */
    private static Document createDocument(String docContent, String[] tokens, int docId){
        Document d = new Document();
        d.setDocId(docId);
        d.setDocumentContent(docContent);
        d.setTermFreqMap(tokens);
        return d;
    }

    /**
     * Indexing a document to the Inverted Index
     * @param tokens array of tokens string of a document
     * @param docId the document ID
     */
    private void indexDocument(String[] tokens, int docId){
        for(int i = 0; i < tokens.length; i++){
            String token = tokens[i];
            
            Set<Integer> docSet = invertedIndex.containsKey(token) ? invertedIndex.get(token) : new TreeSet<>();
            docSet.add(docId);
            invertedIndex.put(token, docSet);
            
            int tokenCount = tokenFreq.containsKey(token) ? tokenFreq.get(token) : 0;
            tokenFreq.put(token,tokenCount + 1);   
        }
    }

    /**
     * Generate the TF-IDF value of all the tokens and documents in the index
     */
    private void generateTFIDF(){
        // iterate through all the documents on the corpus
        for (Document doc : documents.values()) {
            Map<String, Integer> docTfMap = doc.getTermFrequencyMap();
            double docNorm = 0;
            // iterate through all the terms/tokens in the document
            for (String term : docTfMap.keySet()) {
                double tf = 1d + Math.log(docTfMap.get(term));
                double tfidf = (tf * (Math.log(documents.size()+1 / invertedIndex.get(term).size())));
                
                if((doc.getDocId() == 385 || 
                   doc.getDocId() == 72 || 
                   doc.getDocId() == 224) && 
                   (term.matches("school") ||
                    term.matches("kids") ||
                    term.matches("really"))
                ){
                    System.out.println("docID: "+doc.getDocId()+" token: "+term+" raw tf: "+docTfMap.get(term)+" tf: "+tf + " docSize: "+documents.size()+" docFreq: "+invertedIndex.get(term).size()+" idf: "+(Math.log(documents.size() / invertedIndex.get(term).size()))+" tf-idf: "+tfidf);
                }
                
                // put the tf-idf value to the document object
                doc.getTfidfMap().put(term, tfidf);
                
                // also calculate the document normalization value for cosine similarity
                docNorm += Math.pow(tfidf, 2d);
            }
            // document norm  (vector length or L2 norm) || d ||
            doc.setDocNormalizer(Math.sqrt(docNorm)); // == square root (sigma(tfidf^2))
        }
    }
    
    /**
     * Update the tokens statistics on the inverted index
     */
    private void updateTokenStatDisplay(){
        /* UPDATE THE STATISTICS NUMBERS*/
        numOfDocsLabel.setText(String.valueOf(numOfDoc));
        numOfTokensLabel.setText(String.valueOf(numOfToken));
        numOfUniqTokensLabel.setText(String.valueOf(invertedIndex.size()));
        
        /* UPDATE THE TOKEN FREQUENCIES TABLE */
        int i = 0;
        
        tokenStatTable.setRowSorter(null); // remove the sorting
        DefaultTableModel dtm = (DefaultTableModel)tokenStatTable.getModel();
        dtm.getDataVector().removeAllElements();
        
        for(String token : invertedIndex.keySet()){
           dtm.addRow(new Object[] { i+1,token,tokenFreq.get(token), invertedIndex.get(token).size() });
            i++;
        }
        tokenStatTable.setAutoCreateRowSorter(true);
    }
    
    /**
     * This function was intended to be used as a full boolean query
     * @param query
     * @return a set of documents ID
     */
    private static Set<Integer> advanceBooleanSearchDocuments(String query){
        String[] queryTokens = query.split(" ");
        Set s1 = null;
        String prevOperator = "";
        for (String qTok : queryTokens) {
            if (qTok.equals("AND")){
                prevOperator = "AND";
            } else if (qTok.equals("OR")){
                prevOperator = "OR";
            } else if (qTok.equals("NOT")){
                prevOperator = "NOT";
            } else {// just a regular term to search
                if(prevOperator.isEmpty()){
                    s1 = invertedIndex.get(qTok);
                } else {
                    if (prevOperator.equals("AND")){
                        s1 = intersection(s1, invertedIndex.get(qTok));
                    } else if(prevOperator.equals("OR")){
                        s1 = unionSet(s1, invertedIndex.get(qTok));
                    } else if(prevOperator.equals("NOT")){
                        s1 = difference(s1, invertedIndex.get(qTok));
                    }
                }
            }
        }
        return s1;
    }

    /**
     * Search documents that satisfy the query strings
     * @param query the query strings
     * @param isOptimize is the query optimized or not
     * @param numOfComparisonLabel the label that going to show the number of optimization
     * @return 
     */
    private static Set<Integer> booleanSearchDocuments(String query, boolean isOptimize, javax.swing.JLabel numOfComparisonLabel){
        String[] queryTokens;
        
        if(isOptimize) queryTokens = optimizeQueryOrder(query);
        else queryTokens = query.split(" ");
        
        int numOfComp = 0;
        Set s1 = null;
        boolean firstEntry = true;
        
        for (String qTok : queryTokens) {
            if(firstEntry){
                s1 = invertedIndex.get(qTok);
                firstEntry = false;
            } else numOfComp += s1.size();
            
            if(!(s1 == null || s1.isEmpty())) // if we could find the token in the index
                s1 = intersection(s1, invertedIndex.get(qTok));
            else 
                return null; // since we use boolean query, if there's some token that does not available on any document, just simply return null
        }
        
        numOfComparisonLabel.setText(String.valueOf(numOfComp));
        
        return s1;
    }
    
    /**
     * Update the Boolean Query Result Table content
     * @param resultSet a set of document ID from the query result 
     */
    private void updateBooleanQueriesResultTable(Set<Integer> resultSet){
        booleanQueryResultTable.setRowSorter(null); // remove jTable sorting
        DefaultTableModel dtm = (DefaultTableModel)booleanQueryResultTable.getModel();
        dtm.getDataVector().removeAllElements();
        bQueryResultNum.setText("0");
        
        if(resultSet != null){
            resultSet.stream().forEach((docID) -> {
                dtm.addRow(new Object[] {docID, documents.get(docID).getDocContent()});
            });

            bQueryResultNum.setText(String.valueOf(resultSet.size()));
        }
        booleanQueryResultTable.setAutoCreateRowSorter(true); // add jTable sorting capability
    }

    /**
     * Search documents that satisfy the query strings and sort it by weight using cosine similarity
     * @param query the query strings
     * @param isOptimize is the query optimized or not
     * @param numOfComparisonLabel the label that going to show the number of optimization
     * @return 
     */
    private static Map<Integer, Double> weightedSearchDocuments(String query, boolean isOptimize, javax.swing.JLabel numOfComparisonLabel){
        
        String[] queryTokens;
        if(isOptimize){
            queryTokens = optimizeQueryOrder(query);
        } else {
            queryTokens = query.split(" ");
        }
        
        int numOfComp = 0;
        Set s1 = null;
        boolean firstEntry = true;
        
        for (String qTok : queryTokens) {
            if(firstEntry){
                s1 = invertedIndex.get(qTok);
                firstEntry = false;
            }  else numOfComp += s1.size();
            
            if (!(s1 == null || s1.isEmpty())) // if we could find the token in the index
                s1 = intersection(s1, invertedIndex.get(qTok));
            else 
                return null; // since we use boolean query, if there's some token that does not available on any document, just simply return null
            
        }
        
        numOfComparisonLabel.setText(String.valueOf(numOfComp));
        
        // calculate TF-IDF value of the query strings
        QueryDoc qd = calcQueryTfIdf(query);
        
        // calculate the cosine similarity between query and documents
        Map<Integer, Double> weightedDocumentQueryResult = new HashMap<>();
        for (Iterator it = s1.iterator(); it.hasNext();) {
            int docId = (int) it.next();
            weightedDocumentQueryResult.put(docId, calcCosineSim(qd, documents.get(docId)));
        }
        
        return weightedDocumentQueryResult;
    }
    
    /**
     * Calculate the tf-idf value of a query
     * @param query the query string
     * @return Query Document Object
     */
    private static QueryDoc calcQueryTfIdf(String query){
        String[] queryTokens = query.split(" ");//tokenize:
        Map<String, Integer> queryTFMap = new HashMap<>();
        
        for (String queryToken : queryTokens) {
            int tokenCount = queryTFMap.containsKey(queryToken) ? queryTFMap.get(queryToken) : 0;
            queryTFMap.put(queryToken,tokenCount + 1);   
        }
        
        // calculate the tf-idf
        double queryNorm = 0;
        Map<String, Double> queryTfidfMap = new HashMap<>();
        
        for (String queryToken : queryTFMap.keySet()) {
            double tf = 1d + Math.log(queryTFMap.get(queryToken));
            //double tfidf = (tf * (Math.log(documents.size()+1 / invertedIndex.get(queryToken).size()+1)));
            double tfidf = (tf);

            queryTfidfMap.put(queryToken, tfidf);//put the tf-idf value to the document object
            queryNorm += Math.pow(tfidf, 2d);//also calculate the document normalization value for cosine similarity
        }
        // document norm  (vector length or L2 norm) || d ||
        queryNorm = Math.sqrt(queryNorm); // == square root (sigma(tfidf^2))
        System.out.println(queryTfidfMap.toString());
        return new QueryDoc(queryNorm, queryTfidfMap);
    }
    
    /**
     * Calculate cosine similarity between a query and a document
     * @param queryDoc
     * @param doc
     * @return the cosine similarity between the query and the document
     */
    private static double calcCosineSim(QueryDoc queryDoc, Document doc){
        // assumption: the number of tokens in a query would be far more less than
        // the number of tokens in a document
        double similiarity = 0d;
        
        for(String queryToken : queryDoc.queryTfidfMap.keySet()){
            double doc1TfIdfWeight = (queryDoc.queryTfidfMap.get(queryToken));
            
            
            
            if(doc.getTfidfMap().get(queryToken) != null){
                double doc2TfIdfWeight = doc.getTfidfMap().get(queryToken);
                System.out.println("docID: "+doc.getDocId()+" token: "+queryToken+" docTFIDF: "+doc2TfIdfWeight);
//                similiarity += ((doc1TfIdfWeight/queryDoc.queryNormalization)*
//                        (doc2TfIdfWeight/doc.getDocNormalizer()));
                similiarity += ((doc1TfIdfWeight/queryDoc.queryNormalization)*
                        (doc2TfIdfWeight));
                
            }
        }
        
        return (similiarity);
    }
    
    /**
     * Update the Weighted Query Result Table content
     * @param resultMap a Map containing the Document ID and the Weight Value of the document
     */
    private void updateWeigtedQueriesResultTable(Map<Integer, Double> resultMap){
        weightedQueryResultTable.setRowSorter(null); // remove jTable sorting
        DefaultTableModel dtm = (DefaultTableModel)weightedQueryResultTable.getModel();
        dtm.getDataVector().removeAllElements();
        
        int i = 0;
        resultMap = sortByComparator2(resultMap);// sort result by weight
        for (Integer docID : resultMap.keySet()) {
            dtm.addRow(new Object[] {i+1,docID, documents.get(docID).getDocContent(), resultMap.get(docID)});
            i++;
        }
        weightedQueryResultTable.setAutoCreateRowSorter(true); // add jTable sorting capability
        
        wQueryResultNum.setText(String.valueOf(resultMap.size()));
    }
    
    private static Map<String, Set<Integer>> invertedIndex = null;
    private static Map<String, Integer> tokenFreq = null;
    private static Map<Integer, Document> documents = null;
    private static int numOfDoc = 0;
    private static int numOfToken = 0;
    
    private static class QueryDoc{
        double queryNormalization = 0;
        Map<String, Double> queryTfidfMap;
        
        QueryDoc(double queryNormalization, Map<String, Double> queryTfidfMap){
            this.queryNormalization = queryNormalization;
            this.queryTfidfMap = queryTfidfMap;
        }
    }
    
    /**
     * A function that takes query and optimize it by sorting the query
     * strings by the number of documents it could find in the inverted index
     * @param query
     * @return 
     */
    private static String[] optimizeQueryOrder(String query){
        String[] queryTokens = query.split(" ");
        Map<String, Integer> unsortedMap = new HashMap<>();
        
        // get each individual query token number of documents result
        for (String qTok : queryTokens) 
            unsortedMap.put(qTok, invertedIndex.get(qTok).size());
        
        // sort it by the number of document result
        Map<String, Integer> sortedMap = sortByComparator(unsortedMap);
        return sortedMap.keySet().toArray(queryTokens);
    }
    
    /**
     * Helper function to sort a map Object
     * @param unsortMap
     * @return 
     */
    private static Map<String, Integer> sortByComparator(Map<String, Integer> unsortMap) {

        // Convert Map to List
        List<Map.Entry<String, Integer>> list = new LinkedList<>(unsortMap.entrySet());

        // Sort list with comparator, to compare the Map values
        Collections.sort(list, new Comparator<Map.Entry<String, Integer>>() {
            public int compare(Map.Entry<String, Integer> o1,
                    Map.Entry<String, Integer> o2) {
                return (o1.getValue()).compareTo(o2.getValue());
            }
        });

        // Convert sorted map back to a Map
        Map<String, Integer> sortedMap = new LinkedHashMap<String, Integer>();
        for (Iterator<Map.Entry<String, Integer>> it = list.iterator(); it.hasNext();) {
            Map.Entry<String, Integer> entry = it.next();
            sortedMap.put(entry.getKey(), entry.getValue());
        }
        return sortedMap;
    }
    
    /**
     * Helper function to sort a map Object
     * @param unsortMap
     * @return 
     */
    private static Map<Integer, Double> sortByComparator2(Map<Integer, Double> unsortMap) {

        // Convert Map to List
        List<Map.Entry<Integer, Double>> list = new LinkedList<>(unsortMap.entrySet());

        // Sort list with comparator, to compare the Map values
        Collections.sort(list, new Comparator<Map.Entry<Integer, Double>>() {
            public int compare(Map.Entry<Integer, Double> o1, Map.Entry<Integer, Double> o2) {
                return (o2.getValue()).compareTo(o1.getValue());
            }
        });

        // Convert sorted map back to a Map
        Map<Integer, Double> sortedMap = new LinkedHashMap<>();
        for (Iterator<Map.Entry<Integer, Double>> it = list.iterator(); it.hasNext();) {
            Map.Entry<Integer, Double> entry = it.next();
            sortedMap.put(entry.getKey(), entry.getValue());
        }
        return sortedMap;
    }
    
    /**
     * A helper function that union two set
     * @param s1
     * @param s2
     * @return unioned set
     */
    private static HashSet<Integer> unionSet(Set s1, Set s2){ // OR
        HashSet<Integer> union = new HashSet<>(s1);
        union.addAll(s2);
        return union;
    }

    /**
     * A helper function that intersect two set
     * @param s1
     * @param s2
     * @return intersected set
     */
    private static HashSet<Integer> intersection(Set s1, Set s2){ // AND
        HashSet<Integer> intersection = new HashSet<>(s1);
        intersection.retainAll(s2);
        return intersection;
    }
    
    /**
     * A helper function that differs two set
     * @param s1
     * @param s2
     * @return differed set
     */
    private static HashSet<Integer> difference(Set s1, Set s2){ // NOT
        HashSet<Integer> difference = new HashSet<>(s1);
        difference.removeAll(s2);
        return difference;
    }

    public static final String STOPWORDS = "you i the to s a it t and i'";
    public final static String[] SYMBOLS = {
        "\'", "-", ".", "@", "#",
        "!", "\"", "$", "%", "&",
        "(", ")", "*", "+", ",",
        "/", ":", ";", "<", "=",
        ">", "?", "[", "\\", "]",
        "^", "_", "`", "{", "|",
        "}", "~", "—"
    };
    public static final Set<String> PUNCTUATIONSET = new HashSet<>(Arrays.asList(SYMBOLS));
    public static final Set<String> STOPWORDSET = new HashSet<>(Arrays.asList(STOPWORDS.split(" ")));
    private static final JFileChooser FILECHOOSER = new JFileChooser();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorLabel;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JPanel TokenStatPanel;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JLabel bQueryCompLabel;
    private javax.swing.JLabel bQueryCompNum;
    private javax.swing.JLabel bQueryResultLabel;
    private javax.swing.JLabel bQueryResultNum;
    private javax.swing.JTextField booleanQueriesTextField;
    private javax.swing.JPanel booleanQueryPanel;
    private javax.swing.JTable booleanQueryResultTable;
    private javax.swing.JScrollPane booleanQueryScrollPane;
    private javax.swing.JButton booleanSearchButton;
    private javax.swing.JButton corpusFileBrowseButton;
    private javax.swing.JTextField corpusFileTextField;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JCheckBox filterPunctCheckBox;
    private javax.swing.JCheckBox filterStopCheckBox;
    private javax.swing.JButton indexFileButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labIdLabel;
    private javax.swing.JCheckBox lowerCaseCheckBox;
    private javax.swing.JLabel numOfDocStaticLabel;
    private javax.swing.JLabel numOfDocsLabel;
    private javax.swing.JLabel numOfTokStaticLabel;
    private javax.swing.JLabel numOfTokensLabel;
    private javax.swing.JLabel numOfUniqTokStaticLabel;
    private javax.swing.JLabel numOfUniqTokensLabel;
    private javax.swing.JCheckBox optimizeQueryBooleanCheckBox;
    private javax.swing.JCheckBox optimizeQueryWeightedCheckBox;
    private javax.swing.JTable tokenStatTable;
    private javax.swing.JLabel wQueryCompLabel;
    private javax.swing.JLabel wQueryCompNum;
    private javax.swing.JLabel wQueryResultLabel;
    private javax.swing.JLabel wQueryResultNum;
    private javax.swing.JPanel weightedQueryPanel;
    private javax.swing.JTable weightedQueryResultTable;
    private javax.swing.JScrollPane weightedQueryScrollPane;
    private javax.swing.JTextField weightedQueryTextField;
    private javax.swing.JButton weightedSearchButton;
    // End of variables declaration//GEN-END:variables
}
